endpoints:
  - name: multiple config
    group: Proxmox
    url: "https://iot-proxmox.net"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: nas
    group: Proxmox
    url: "https://jonsbo.dev.iot-proxmox.net"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox-dns-query
    group: Proxmox
    url: "192.168.1.1" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "jonsbo.dev.iot-proxmox.net"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.1.159"
      - "[DNS_RCODE] == NOERROR"

  - name: icmp-ping
    group: Proxmox
    url: "icmp://jonsbo.dev.iot-proxmox.net"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: icmp-ping-pve
    group: Proxmox
    url: "icmp://192.168.1.207"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
  
