endpoints:
  - name: truenas dns
    group: NAS
    url: "192.168.1.1" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "truenas.dev.iot-proxmox.net"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.1.159"
      - "[DNS_RCODE] == NOERROR"
      

  - name: icmp-ping-truenas-1
    group: NAS
    url: "icmp://truenas.dev.iot-proxmox.net"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: icmp-ping-truenas
    group: NAS
    url: "icmp://192.168.1.194"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
