services:
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
    - ./_site:/usr/share/nginx/html:ro
    env_file: .env 
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.${SERVER}.iot-proxmox.net`) || Host(`bradfordjones.live`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
networks:
  proxy:
    external: true

    