services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
      #- ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      #- ./backups:/mnt/backups
    ports:
      - "5432:5432"
      
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
    networks:
      postgres_web:

networks:
  postgres_web:
    external: true